SCREW_INDEX = "UNSCREWING_INDEX"

CANT_UNSCREW_LIST = "CANT_UNSCREW_LIST"

CHANGE_TOOL_SCHEDULE_INDEX = "CHANGE_TOOL_SCHEDULE_INDEX"

LIST_OF_SCREWS = "LIST_OF_SCREWS"

TOOL_IN_HAND = "TOOL_IN_HAND"

OPERATION_DONE = "LAST_OPERATION"
OPERATION_INPROGRESS = "OPERATION_INPROGRESS"
