SCREW_INDEX = "UNSCREWING_INDEX"

CANT_UNSCREW_LIST = "CANT_UNSCREW_LIST"

CHANGE_TOOL_SCHEDULE_INDEX = "CHANGE_TOOL_SCHEDULE_INDEX"

LIST_OF_SCREWS = "LIST_OF_SCREWS"

TOOL_IN_HAND = "TOOL_IN_HAND"

OPERATION_DONE = "LAST_OPERATION"
OPERATION_INPROGRESS = "OPERATION_INPROGRESS"

GET_SCREW_SCHEDULE = "GetScrew"
RETURN_SCREW_SCHEDULE = "ReturnScrew"
GET_MILL_SCHEDULE = "GetMill"
RETURN_MILL_SCHEDULE = "ReturnMill"

GET_SCREW_VELOCITY = "GetscrewVel"
GET_SCREW_ACC = "GetscrewAcc"
SCREW_CHECK_FORCE = "screwcheckforce"
GET_SCREW_WAYPOINTS_TYPE = "Getscrewwaypointstype"
GET_SCREW_LIST_WAYPOINTS = "GetscrewListwaypoint"


RETURN_SCREW_WAYPOINTS = "returnscrewwaypoint"
RETURN_SCREW_VEL = "returnScrewVel"
RETURN_SCREW_CHECK_FORCE = "returnscrewcheckforce"
RETURN_SCREW_ACC = "returnScrewAcc"
RETURN_SCREW_WAYPOINTS_TYPE = "returnscrewwaypointstype"


GET_MILL_VEL = "GetMillVel"
GET_MILL_ACC = "GetsMillAcc"
MILL_CHECK_FORCE = "Millcheckforce"
GET_MILL_WAYPOINTS_TYPE = "GetMillwaypointstype"
GET_MILLING_WAYPOINTS = "getMillingWaypoints"

RETURN_MILL_VEL = "returnMillVel"
RETURN_MILL_CHECK_FORCE = "returnMillcheckforce"
RETURN_MILL_ACC = "returnMillAcc"
RETURN_MILL_WAYPOINTS_TYPE = "returnMillwaypointstype"
RETURN_MILL_WAYPOINTS = "returnMillWaypoints"


VEL = "VEL"
ACC = "ACC"
CHECK_FORCE = "CHECK_FORCE"
WAYPOINTS_TYPES = "WAYPOINTS_TYPES"
WAYPOINTS = "WAYPOINTS"






