; Auto-generated. Do not edit!


(cl:in-package abb_robot_msgs-msg)


;//! \htmlinclude ServiceResponses.msg.html

(cl:defclass <ServiceResponses> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ServiceResponses (<ServiceResponses>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ServiceResponses>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ServiceResponses)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name abb_robot_msgs-msg:<ServiceResponses> is deprecated: use abb_robot_msgs-msg:ServiceResponses instead.")))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<ServiceResponses>)))
    "Constants for message type '<ServiceResponses>"
  '((:SUCCESS . "\"\"")
    (:RC_SUCCESS . 1)
    (:FAILED . "\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\"")
    (:RC_FAILED . 2)
    (:SERVER_IS_BUSY . "\"Server is busy\"")
    (:RC_SERVER_IS_BUSY . 1001)
    (:EMPTY_FILENAME . "\"Filename is empty\"")
    (:RC_EMPTY_FILENAME . 2001)
    (:EMPTY_SIGNAL_NAME . "\"Signal name is empty\"")
    (:RC_EMPTY_SIGNAL_NAME . 2002)
    (:EMPTY_RAPID_TASK_NAME . "\"RAPID task name is empty\"")
    (:RC_EMPTY_RAPID_TASK_NAME . 2003)
    (:EMPTY_RAPID_MODULE_NAME . "\"RAPID module name is empty\"")
    (:RC_EMPTY_RAPID_MODULE_NAME . 2004)
    (:EMPTY_RAPID_SYMBOL_NAME . "\"RAPID symbol name is empty\"")
    (:RC_EMPTY_RAPID_SYMBOL_NAME . 2005)
    (:NOT_IN_AUTO_MODE . "\"Robot controller is not in AUTO mode\"")
    (:RC_NOT_IN_AUTO_MODE . 3001)
    (:MOTORS_ARE_OFF . "\"Motors are off\"")
    (:RC_MOTORS_ARE_OFF . 3002)
    (:MOTORS_ARE_ON . "\"Motors are on\"")
    (:RC_MOTORS_ARE_ON . 3003)
    (:RAPID_NOT_STOPPED . "\"RAPID has not been stopped\"")
    (:RC_RAPID_NOT_STOPPED . 3004)
    (:RAPID_NOT_RUNNING . "\"RAPID is not running\"")
    (:RC_RAPID_NOT_RUNNING . 3005)
    (:SM_RUNTIME_STATES_MISSING . "\"No runtime states received for any StateMachine Add-In instance\"")
    (:RC_SM_RUNTIME_STATES_MISSING . 4001)
    (:SM_UNKNOWN_RAPID_TASK . "\"RAPID task not found among known StateMachine Add-In instances\"")
    (:RC_SM_UNKNOWN_RAPID_TASK . 4002)
    (:SM_UNINITIALIZED . "\"StateMachine Add-In instance has not been initialized\"")
    (:RC_SM_UNINITIALIZED . 4003))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'ServiceResponses)))
    "Constants for message type 'ServiceResponses"
  '((:SUCCESS . "\"\"")
    (:RC_SUCCESS . 1)
    (:FAILED . "\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\"")
    (:RC_FAILED . 2)
    (:SERVER_IS_BUSY . "\"Server is busy\"")
    (:RC_SERVER_IS_BUSY . 1001)
    (:EMPTY_FILENAME . "\"Filename is empty\"")
    (:RC_EMPTY_FILENAME . 2001)
    (:EMPTY_SIGNAL_NAME . "\"Signal name is empty\"")
    (:RC_EMPTY_SIGNAL_NAME . 2002)
    (:EMPTY_RAPID_TASK_NAME . "\"RAPID task name is empty\"")
    (:RC_EMPTY_RAPID_TASK_NAME . 2003)
    (:EMPTY_RAPID_MODULE_NAME . "\"RAPID module name is empty\"")
    (:RC_EMPTY_RAPID_MODULE_NAME . 2004)
    (:EMPTY_RAPID_SYMBOL_NAME . "\"RAPID symbol name is empty\"")
    (:RC_EMPTY_RAPID_SYMBOL_NAME . 2005)
    (:NOT_IN_AUTO_MODE . "\"Robot controller is not in AUTO mode\"")
    (:RC_NOT_IN_AUTO_MODE . 3001)
    (:MOTORS_ARE_OFF . "\"Motors are off\"")
    (:RC_MOTORS_ARE_OFF . 3002)
    (:MOTORS_ARE_ON . "\"Motors are on\"")
    (:RC_MOTORS_ARE_ON . 3003)
    (:RAPID_NOT_STOPPED . "\"RAPID has not been stopped\"")
    (:RC_RAPID_NOT_STOPPED . 3004)
    (:RAPID_NOT_RUNNING . "\"RAPID is not running\"")
    (:RC_RAPID_NOT_RUNNING . 3005)
    (:SM_RUNTIME_STATES_MISSING . "\"No runtime states received for any StateMachine Add-In instance\"")
    (:RC_SM_RUNTIME_STATES_MISSING . 4001)
    (:SM_UNKNOWN_RAPID_TASK . "\"RAPID task not found among known StateMachine Add-In instances\"")
    (:RC_SM_UNKNOWN_RAPID_TASK . 4002)
    (:SM_UNINITIALIZED . "\"StateMachine Add-In instance has not been initialized\"")
    (:RC_SM_UNINITIALIZED . 4003))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ServiceResponses>) ostream)
  "Serializes a message object of type '<ServiceResponses>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ServiceResponses>) istream)
  "Deserializes a message object of type '<ServiceResponses>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ServiceResponses>)))
  "Returns string type for a message object of type '<ServiceResponses>"
  "abb_robot_msgs/ServiceResponses")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ServiceResponses)))
  "Returns string type for a message object of type 'ServiceResponses"
  "abb_robot_msgs/ServiceResponses")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ServiceResponses>)))
  "Returns md5sum for a message object of type '<ServiceResponses>"
  "c541477c2ff72df8851a0d0cd0b0b782")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ServiceResponses)))
  "Returns md5sum for a message object of type 'ServiceResponses"
  "c541477c2ff72df8851a0d0cd0b0b782")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ServiceResponses>)))
  "Returns full string definition for message of type '<ServiceResponses>"
  (cl:format cl:nil "# result codes are 16 bit unsigned~%~%# Generic OK~%string SUCCESS=\"\"~%uint16 RC_SUCCESS=1~%~%# Generic failure message~%string FAILED=\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\"~%uint16 RC_FAILED=2~%~%# The server's underlying communication interface is busy~%string SERVER_IS_BUSY=\"Server is busy\"~%uint16 RC_SERVER_IS_BUSY=1001~%~%# Filename field is empty in service request~%string EMPTY_FILENAME=\"Filename is empty\"~%uint16 RC_EMPTY_FILENAME=2001~%~%# Signal name field is empty in service request~%string EMPTY_SIGNAL_NAME=\"Signal name is empty\"~%uint16 RC_EMPTY_SIGNAL_NAME=2002~%~%# RAPID task name field is empty in service request~%string EMPTY_RAPID_TASK_NAME=\"RAPID task name is empty\"~%uint16 RC_EMPTY_RAPID_TASK_NAME=2003~%~%# RAPID module name field is empty in service request~%string EMPTY_RAPID_MODULE_NAME=\"RAPID module name is empty\"~%uint16 RC_EMPTY_RAPID_MODULE_NAME=2004~%~%# RAPID symbol name field is empty in service request~%string EMPTY_RAPID_SYMBOL_NAME=\"RAPID symbol name is empty\"~%uint16 RC_EMPTY_RAPID_SYMBOL_NAME=2005~%~%# Robot controller is not in auto mode~%string NOT_IN_AUTO_MODE=\"Robot controller is not in AUTO mode\"~%uint16 RC_NOT_IN_AUTO_MODE=3001~%~%# The motors are off~%string MOTORS_ARE_OFF=\"Motors are off\"~%uint16 RC_MOTORS_ARE_OFF=3002~%~%# The motors are on~%string MOTORS_ARE_ON=\"Motors are on\"~%uint16 RC_MOTORS_ARE_ON=3003~%~%# RAPID has not been stopped~%string RAPID_NOT_STOPPED=\"RAPID has not been stopped\"~%uint16 RC_RAPID_NOT_STOPPED=3004~%~%# RAPID is not running~%string RAPID_NOT_RUNNING=\"RAPID is not running\"~%uint16 RC_RAPID_NOT_RUNNING=3005~%~%# RobotWare StateMachine Add-In runtime state is missing~%string SM_RUNTIME_STATES_MISSING=\"No runtime states received for any StateMachine Add-In instance\"~%uint16 RC_SM_RUNTIME_STATES_MISSING=4001~%~%# RobotWare StateMachine Add-In-instances do not know RAPID task~%string SM_UNKNOWN_RAPID_TASK=\"RAPID task not found among known StateMachine Add-In instances\"~%uint16 RC_SM_UNKNOWN_RAPID_TASK=4002~%~%# RobotWare StateMachine Add-In instance has not been initialized~%string SM_UNINITIALIZED=\"StateMachine Add-In instance has not been initialized\"~%uint16 RC_SM_UNINITIALIZED=4003~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ServiceResponses)))
  "Returns full string definition for message of type 'ServiceResponses"
  (cl:format cl:nil "# result codes are 16 bit unsigned~%~%# Generic OK~%string SUCCESS=\"\"~%uint16 RC_SUCCESS=1~%~%# Generic failure message~%string FAILED=\"Service failed (e.g. timeout or resource not found, see the DEBUG log for details)\"~%uint16 RC_FAILED=2~%~%# The server's underlying communication interface is busy~%string SERVER_IS_BUSY=\"Server is busy\"~%uint16 RC_SERVER_IS_BUSY=1001~%~%# Filename field is empty in service request~%string EMPTY_FILENAME=\"Filename is empty\"~%uint16 RC_EMPTY_FILENAME=2001~%~%# Signal name field is empty in service request~%string EMPTY_SIGNAL_NAME=\"Signal name is empty\"~%uint16 RC_EMPTY_SIGNAL_NAME=2002~%~%# RAPID task name field is empty in service request~%string EMPTY_RAPID_TASK_NAME=\"RAPID task name is empty\"~%uint16 RC_EMPTY_RAPID_TASK_NAME=2003~%~%# RAPID module name field is empty in service request~%string EMPTY_RAPID_MODULE_NAME=\"RAPID module name is empty\"~%uint16 RC_EMPTY_RAPID_MODULE_NAME=2004~%~%# RAPID symbol name field is empty in service request~%string EMPTY_RAPID_SYMBOL_NAME=\"RAPID symbol name is empty\"~%uint16 RC_EMPTY_RAPID_SYMBOL_NAME=2005~%~%# Robot controller is not in auto mode~%string NOT_IN_AUTO_MODE=\"Robot controller is not in AUTO mode\"~%uint16 RC_NOT_IN_AUTO_MODE=3001~%~%# The motors are off~%string MOTORS_ARE_OFF=\"Motors are off\"~%uint16 RC_MOTORS_ARE_OFF=3002~%~%# The motors are on~%string MOTORS_ARE_ON=\"Motors are on\"~%uint16 RC_MOTORS_ARE_ON=3003~%~%# RAPID has not been stopped~%string RAPID_NOT_STOPPED=\"RAPID has not been stopped\"~%uint16 RC_RAPID_NOT_STOPPED=3004~%~%# RAPID is not running~%string RAPID_NOT_RUNNING=\"RAPID is not running\"~%uint16 RC_RAPID_NOT_RUNNING=3005~%~%# RobotWare StateMachine Add-In runtime state is missing~%string SM_RUNTIME_STATES_MISSING=\"No runtime states received for any StateMachine Add-In instance\"~%uint16 RC_SM_RUNTIME_STATES_MISSING=4001~%~%# RobotWare StateMachine Add-In-instances do not know RAPID task~%string SM_UNKNOWN_RAPID_TASK=\"RAPID task not found among known StateMachine Add-In instances\"~%uint16 RC_SM_UNKNOWN_RAPID_TASK=4002~%~%# RobotWare StateMachine Add-In instance has not been initialized~%string SM_UNINITIALIZED=\"StateMachine Add-In instance has not been initialized\"~%uint16 RC_SM_UNINITIALIZED=4003~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ServiceResponses>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ServiceResponses>))
  "Converts a ROS message object to a list"
  (cl:list 'ServiceResponses
))
