(cl:defpackage abb_rapid_sm_addin_msgs-msg
  (:use )
  (:export
   "<EGMACTIVATESETTINGS>"
   "EGMACTIVATESETTINGS"
   "<EGMRUNSETTINGS>"
   "EGMRUNSETTINGS"
   "<EGMSETTINGS>"
   "EGMSETTINGS"
   "<EGMSETUPSETTINGS>"
   "EGMSETUPSETTINGS"
   "<EGMSTOPSETTINGS>"
   "EGMSTOPSETTINGS"
   "<RUNTIMESTATE>"
   "RUNTIMESTATE"
   "<STATEMACHINESTATE>"
   "STATEMACHINESTATE"
  ))

