// Generated by gencpp from file abb_robot_msgs/GetIOSignal.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_GETIOSIGNAL_H
#define ABB_ROBOT_MSGS_MESSAGE_GETIOSIGNAL_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/GetIOSignalRequest.h>
#include <abb_robot_msgs/GetIOSignalResponse.h>


namespace abb_robot_msgs
{

struct GetIOSignal
{

typedef GetIOSignalRequest Request;
typedef GetIOSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIOSignal
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::GetIOSignal > {
  static const char* value()
  {
    return "edcf90cd349492ba1ca9cc7d13c4954a";
  }

  static const char* value(const ::abb_robot_msgs::GetIOSignal&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::GetIOSignal > {
  static const char* value()
  {
    return "abb_robot_msgs/GetIOSignal";
  }

  static const char* value(const ::abb_robot_msgs::GetIOSignal&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::GetIOSignalRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetIOSignal >
template<>
struct MD5Sum< ::abb_robot_msgs::GetIOSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetIOSignal >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetIOSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetIOSignalRequest> should match
// service_traits::DataType< ::abb_robot_msgs::GetIOSignal >
template<>
struct DataType< ::abb_robot_msgs::GetIOSignalRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetIOSignal >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetIOSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::GetIOSignalResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetIOSignal >
template<>
struct MD5Sum< ::abb_robot_msgs::GetIOSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetIOSignal >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetIOSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetIOSignalResponse> should match
// service_traits::DataType< ::abb_robot_msgs::GetIOSignal >
template<>
struct DataType< ::abb_robot_msgs::GetIOSignalResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetIOSignal >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetIOSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_GETIOSIGNAL_H
