// Generated by gencpp from file abb_robot_msgs/GetRobotControllerDescription.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_GETROBOTCONTROLLERDESCRIPTION_H
#define ABB_ROBOT_MSGS_MESSAGE_GETROBOTCONTROLLERDESCRIPTION_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/GetRobotControllerDescriptionRequest.h>
#include <abb_robot_msgs/GetRobotControllerDescriptionResponse.h>


namespace abb_robot_msgs
{

struct GetRobotControllerDescription
{

typedef GetRobotControllerDescriptionRequest Request;
typedef GetRobotControllerDescriptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotControllerDescription
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::GetRobotControllerDescription > {
  static const char* value()
  {
    return "7c2a2ccf1dbdb360e4b26d80a3725b92";
  }

  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescription&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::GetRobotControllerDescription > {
  static const char* value()
  {
    return "abb_robot_msgs/GetRobotControllerDescription";
  }

  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescription&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::GetRobotControllerDescriptionRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetRobotControllerDescription >
template<>
struct MD5Sum< ::abb_robot_msgs::GetRobotControllerDescriptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetRobotControllerDescription >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetRobotControllerDescriptionRequest> should match
// service_traits::DataType< ::abb_robot_msgs::GetRobotControllerDescription >
template<>
struct DataType< ::abb_robot_msgs::GetRobotControllerDescriptionRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetRobotControllerDescription >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::GetRobotControllerDescriptionResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetRobotControllerDescription >
template<>
struct MD5Sum< ::abb_robot_msgs::GetRobotControllerDescriptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetRobotControllerDescription >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescriptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetRobotControllerDescriptionResponse> should match
// service_traits::DataType< ::abb_robot_msgs::GetRobotControllerDescription >
template<>
struct DataType< ::abb_robot_msgs::GetRobotControllerDescriptionResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetRobotControllerDescription >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetRobotControllerDescriptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_GETROBOTCONTROLLERDESCRIPTION_H
