// Generated by gencpp from file abb_robot_msgs/GetSpeedRatio.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_GETSPEEDRATIO_H
#define ABB_ROBOT_MSGS_MESSAGE_GETSPEEDRATIO_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/GetSpeedRatioRequest.h>
#include <abb_robot_msgs/GetSpeedRatioResponse.h>


namespace abb_robot_msgs
{

struct GetSpeedRatio
{

typedef GetSpeedRatioRequest Request;
typedef GetSpeedRatioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSpeedRatio
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::GetSpeedRatio > {
  static const char* value()
  {
    return "f0753046e29c5c4aa8b7b9ff8a761daf";
  }

  static const char* value(const ::abb_robot_msgs::GetSpeedRatio&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::GetSpeedRatio > {
  static const char* value()
  {
    return "abb_robot_msgs/GetSpeedRatio";
  }

  static const char* value(const ::abb_robot_msgs::GetSpeedRatio&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::GetSpeedRatioRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetSpeedRatio >
template<>
struct MD5Sum< ::abb_robot_msgs::GetSpeedRatioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetSpeedRatioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetSpeedRatioRequest> should match
// service_traits::DataType< ::abb_robot_msgs::GetSpeedRatio >
template<>
struct DataType< ::abb_robot_msgs::GetSpeedRatioRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetSpeedRatioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::GetSpeedRatioResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::GetSpeedRatio >
template<>
struct MD5Sum< ::abb_robot_msgs::GetSpeedRatioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::GetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetSpeedRatioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::GetSpeedRatioResponse> should match
// service_traits::DataType< ::abb_robot_msgs::GetSpeedRatio >
template<>
struct DataType< ::abb_robot_msgs::GetSpeedRatioResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::GetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::GetSpeedRatioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_GETSPEEDRATIO_H
