// Generated by gencpp from file abb_robot_msgs/SetFileContents.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_SETFILECONTENTS_H
#define ABB_ROBOT_MSGS_MESSAGE_SETFILECONTENTS_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/SetFileContentsRequest.h>
#include <abb_robot_msgs/SetFileContentsResponse.h>


namespace abb_robot_msgs
{

struct SetFileContents
{

typedef SetFileContentsRequest Request;
typedef SetFileContentsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFileContents
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::SetFileContents > {
  static const char* value()
  {
    return "b9fd3989a30f4c529cc017e54ab4c80f";
  }

  static const char* value(const ::abb_robot_msgs::SetFileContents&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::SetFileContents > {
  static const char* value()
  {
    return "abb_robot_msgs/SetFileContents";
  }

  static const char* value(const ::abb_robot_msgs::SetFileContents&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::SetFileContentsRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetFileContents >
template<>
struct MD5Sum< ::abb_robot_msgs::SetFileContentsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetFileContents >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetFileContentsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetFileContentsRequest> should match
// service_traits::DataType< ::abb_robot_msgs::SetFileContents >
template<>
struct DataType< ::abb_robot_msgs::SetFileContentsRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetFileContents >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetFileContentsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::SetFileContentsResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetFileContents >
template<>
struct MD5Sum< ::abb_robot_msgs::SetFileContentsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetFileContents >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetFileContentsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetFileContentsResponse> should match
// service_traits::DataType< ::abb_robot_msgs::SetFileContents >
template<>
struct DataType< ::abb_robot_msgs::SetFileContentsResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetFileContents >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetFileContentsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_SETFILECONTENTS_H
