// Generated by gencpp from file abb_robot_msgs/SetIOSignalRequest.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_SETIOSIGNALREQUEST_H
#define ABB_ROBOT_MSGS_MESSAGE_SETIOSIGNALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abb_robot_msgs
{
template <class ContainerAllocator>
struct SetIOSignalRequest_
{
  typedef SetIOSignalRequest_<ContainerAllocator> Type;

  SetIOSignalRequest_()
    : signal()
    , value()  {
    }
  SetIOSignalRequest_(const ContainerAllocator& _alloc)
    : signal(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _signal_type;
  _signal_type signal;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIOSignalRequest_

typedef ::abb_robot_msgs::SetIOSignalRequest_<std::allocator<void> > SetIOSignalRequest;

typedef boost::shared_ptr< ::abb_robot_msgs::SetIOSignalRequest > SetIOSignalRequestPtr;
typedef boost::shared_ptr< ::abb_robot_msgs::SetIOSignalRequest const> SetIOSignalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator1> & lhs, const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator1> & lhs, const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abb_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17cb31e0dfb7106dce1621cc1fa3f3bf";
  }

  static const char* value(const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17cb31e0dfb7106dULL;
  static const uint64_t static_value2 = 0xce1621cc1fa3f3bfULL;
};

template<class ContainerAllocator>
struct DataType< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb_robot_msgs/SetIOSignalRequest";
  }

  static const char* value(const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#-------------------------------------------------------------------------------\n"
"# Description:\n"
"#   The purpose of this service definition, is to define a way to set the\n"
"#   value of an IO-signal defined in an ABB robot controller system.\n"
"#-------------------------------------------------------------------------------\n"
"\n"
"#-------------------------------------------------------------------------------\n"
"# Service request fields\n"
"#-------------------------------------------------------------------------------\n"
"# Name of the targeted IO-signal.\n"
"string signal\n"
"\n"
"# New value for the IO-signal.\n"
"string value\n"
"\n"
;
  }

  static const char* value(const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIOSignalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abb_robot_msgs::SetIOSignalRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.signal);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_SETIOSIGNALREQUEST_H
