// Generated by gencpp from file abb_robot_msgs/SetRAPIDNum.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_SETRAPIDNUM_H
#define ABB_ROBOT_MSGS_MESSAGE_SETRAPIDNUM_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/SetRAPIDNumRequest.h>
#include <abb_robot_msgs/SetRAPIDNumResponse.h>


namespace abb_robot_msgs
{

struct SetRAPIDNum
{

typedef SetRAPIDNumRequest Request;
typedef SetRAPIDNumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRAPIDNum
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDNum > {
  static const char* value()
  {
    return "4108cd886758eb287b6fb706804d2b63";
  }

  static const char* value(const ::abb_robot_msgs::SetRAPIDNum&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::SetRAPIDNum > {
  static const char* value()
  {
    return "abb_robot_msgs/SetRAPIDNum";
  }

  static const char* value(const ::abb_robot_msgs::SetRAPIDNum&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDNumRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDNum >
template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDNumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetRAPIDNum >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDNumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetRAPIDNumRequest> should match
// service_traits::DataType< ::abb_robot_msgs::SetRAPIDNum >
template<>
struct DataType< ::abb_robot_msgs::SetRAPIDNumRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetRAPIDNum >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDNumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDNumResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDNum >
template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDNumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetRAPIDNum >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDNumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetRAPIDNumResponse> should match
// service_traits::DataType< ::abb_robot_msgs::SetRAPIDNum >
template<>
struct DataType< ::abb_robot_msgs::SetRAPIDNumResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetRAPIDNum >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDNumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_SETRAPIDNUM_H
