// Generated by gencpp from file abb_robot_msgs/SetRAPIDBool.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_SETRAPIDBOOL_H
#define ABB_ROBOT_MSGS_MESSAGE_SETRAPIDBOOL_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/SetRAPIDBoolRequest.h>
#include <abb_robot_msgs/SetRAPIDBoolResponse.h>


namespace abb_robot_msgs
{

struct SetRAPIDBool
{

typedef SetRAPIDBoolRequest Request;
typedef SetRAPIDBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRAPIDBool
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDBool > {
  static const char* value()
  {
    return "932d876676bb80924a225c457e4d06a3";
  }

  static const char* value(const ::abb_robot_msgs::SetRAPIDBool&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::SetRAPIDBool > {
  static const char* value()
  {
    return "abb_robot_msgs/SetRAPIDBool";
  }

  static const char* value(const ::abb_robot_msgs::SetRAPIDBool&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDBoolRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDBool >
template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetRAPIDBool >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetRAPIDBoolRequest> should match
// service_traits::DataType< ::abb_robot_msgs::SetRAPIDBool >
template<>
struct DataType< ::abb_robot_msgs::SetRAPIDBoolRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetRAPIDBool >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDBoolResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetRAPIDBool >
template<>
struct MD5Sum< ::abb_robot_msgs::SetRAPIDBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetRAPIDBool >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetRAPIDBoolResponse> should match
// service_traits::DataType< ::abb_robot_msgs::SetRAPIDBool >
template<>
struct DataType< ::abb_robot_msgs::SetRAPIDBoolResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetRAPIDBool >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetRAPIDBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_SETRAPIDBOOL_H
