// Generated by gencpp from file abb_robot_msgs/SetSpeedRatio.msg
// DO NOT EDIT!


#ifndef ABB_ROBOT_MSGS_MESSAGE_SETSPEEDRATIO_H
#define ABB_ROBOT_MSGS_MESSAGE_SETSPEEDRATIO_H

#include <ros/service_traits.h>


#include <abb_robot_msgs/SetSpeedRatioRequest.h>
#include <abb_robot_msgs/SetSpeedRatioResponse.h>


namespace abb_robot_msgs
{

struct SetSpeedRatio
{

typedef SetSpeedRatioRequest Request;
typedef SetSpeedRatioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeedRatio
} // namespace abb_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_robot_msgs::SetSpeedRatio > {
  static const char* value()
  {
    return "a37a98881c87fe9569621a0efb03c471";
  }

  static const char* value(const ::abb_robot_msgs::SetSpeedRatio&) { return value(); }
};

template<>
struct DataType< ::abb_robot_msgs::SetSpeedRatio > {
  static const char* value()
  {
    return "abb_robot_msgs/SetSpeedRatio";
  }

  static const char* value(const ::abb_robot_msgs::SetSpeedRatio&) { return value(); }
};


// service_traits::MD5Sum< ::abb_robot_msgs::SetSpeedRatioRequest> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetSpeedRatio >
template<>
struct MD5Sum< ::abb_robot_msgs::SetSpeedRatioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetSpeedRatioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetSpeedRatioRequest> should match
// service_traits::DataType< ::abb_robot_msgs::SetSpeedRatio >
template<>
struct DataType< ::abb_robot_msgs::SetSpeedRatioRequest>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetSpeedRatioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_robot_msgs::SetSpeedRatioResponse> should match
// service_traits::MD5Sum< ::abb_robot_msgs::SetSpeedRatio >
template<>
struct MD5Sum< ::abb_robot_msgs::SetSpeedRatioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_robot_msgs::SetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetSpeedRatioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_robot_msgs::SetSpeedRatioResponse> should match
// service_traits::DataType< ::abb_robot_msgs::SetSpeedRatio >
template<>
struct DataType< ::abb_robot_msgs::SetSpeedRatioResponse>
{
  static const char* value()
  {
    return DataType< ::abb_robot_msgs::SetSpeedRatio >::value();
  }
  static const char* value(const ::abb_robot_msgs::SetSpeedRatioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_ROBOT_MSGS_MESSAGE_SETSPEEDRATIO_H
