(cl:defpackage abb_rapid_sm_addin_msgs-srv
  (:use )
  (:export
   "GETEGMSETTINGS"
   "<GETEGMSETTINGS-REQUEST>"
   "GETEGMSETTINGS-REQUEST"
   "<GETEGMSETTINGS-RESPONSE>"
   "GETEGMSETTINGS-RESPONSE"
   "SETEGMSETTINGS"
   "<SETEGMSETTINGS-REQUEST>"
   "SETEGMSETTINGS-REQUEST"
   "<SETEGMSETTINGS-RESPONSE>"
   "SETEGMSETTINGS-RESPONSE"
   "SETRAPIDROUTINE"
   "<SETRAPIDROUTINE-REQUEST>"
   "SETRAPIDROUTINE-REQUEST"
   "<SETRAPIDROUTINE-RESPONSE>"
   "SETRAPIDROUTINE-RESPONSE"
   "SETSGCOMMAND"
   "<SETSGCOMMAND-REQUEST>"
   "SETSGCOMMAND-REQUEST"
   "<SETSGCOMMAND-RESPONSE>"
   "SETSGCOMMAND-RESPONSE"
  ))

