// Generated by gencpp from file CentralNode/ScrewList.msg
// DO NOT EDIT!


#ifndef CENTRALNODE_MESSAGE_SCREWLIST_H
#define CENTRALNODE_MESSAGE_SCREWLIST_H

#include <ros/service_traits.h>


#include <CentralNode/ScrewListRequest.h>
#include <CentralNode/ScrewListResponse.h>


namespace CentralNode
{

struct ScrewList
{

typedef ScrewListRequest Request;
typedef ScrewListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScrewList
} // namespace CentralNode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::CentralNode::ScrewList > {
  static const char* value()
  {
    return "2f6d262f128183ca8a94edda08422d99";
  }

  static const char* value(const ::CentralNode::ScrewList&) { return value(); }
};

template<>
struct DataType< ::CentralNode::ScrewList > {
  static const char* value()
  {
    return "CentralNode/ScrewList";
  }

  static const char* value(const ::CentralNode::ScrewList&) { return value(); }
};


// service_traits::MD5Sum< ::CentralNode::ScrewListRequest> should match
// service_traits::MD5Sum< ::CentralNode::ScrewList >
template<>
struct MD5Sum< ::CentralNode::ScrewListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::CentralNode::ScrewList >::value();
  }
  static const char* value(const ::CentralNode::ScrewListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::CentralNode::ScrewListRequest> should match
// service_traits::DataType< ::CentralNode::ScrewList >
template<>
struct DataType< ::CentralNode::ScrewListRequest>
{
  static const char* value()
  {
    return DataType< ::CentralNode::ScrewList >::value();
  }
  static const char* value(const ::CentralNode::ScrewListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::CentralNode::ScrewListResponse> should match
// service_traits::MD5Sum< ::CentralNode::ScrewList >
template<>
struct MD5Sum< ::CentralNode::ScrewListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::CentralNode::ScrewList >::value();
  }
  static const char* value(const ::CentralNode::ScrewListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::CentralNode::ScrewListResponse> should match
// service_traits::DataType< ::CentralNode::ScrewList >
template<>
struct DataType< ::CentralNode::ScrewListResponse>
{
  static const char* value()
  {
    return DataType< ::CentralNode::ScrewList >::value();
  }
  static const char* value(const ::CentralNode::ScrewListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CENTRALNODE_MESSAGE_SCREWLIST_H
